name: OnlyZombies
version: '${project.version}'
main: dev.neuralnexus.onlyzombies.OnlyZombies
commands:
  zspawngroup:
    description: "Spawn a group of zombies"
    usage: "/zspawngroup <amount>"
    permission: oz.zspawngroup
    aliases: [zsg]
  zspawnhorde:
    description: "Spawn a horde of zombies"
    usage: "/zspawnhorde <amount> <region>"
    permission: oz.zspawnhorde
    aliases: [zsh]